### ISSUE TITLE
メモリアロケーターのfeature化

### ISSUE THREAD

**Issue by satler-git** [satler-git/etymora#6]
```toml
[features]
default = []
mimalloc = [ "mimalloc" ]
jemalloc = [ "jemallocator" ]
```

```rust
#[cfg(feature = "mimalloc")]
#[global_allocator]
static ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

#[cfg(all(feature = "jemalloc", not(target_env = "msvc")))]
#[global_allocator]
static ALLOC: jemallocator::Jemalloc = jemallocator::Jemalloc;
```
